version: '3.8'

services:
  mysql:
    image: mysql:8.1.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

  prisma:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - ${PR_PORT}:${PR_PORT}
    depends_on:
      - mysql
    environment:
      API_PORT: ${API_PORT}
    command: [ "tail", "-f", "/dev/null" ]
volumes:
  mysql_data:
